# Generated by Django 6.0.3 on 2026-03-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_make_owner_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracted',
            name='bounding_box',
            field=models.JSONField(blank=True, help_text='Table location as {x0, y0, x1, y1} coordinates', null=True),
        ),
        migrations.AddField(
            model_name='extracted',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Extraction confidence score from 0.0 to 1.0', null=True),
        ),
        migrations.AddField(
            model_name='extracted',
            name='extraction_method',
            field=models.CharField(blank=True, help_text='Method used to extract the table (e.g., camelot-lattice, pdfplumber)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extracted',
            name='page_type',
            field=models.CharField(blank=True, choices=[('born_digital', 'Born Digital'), ('scanned', 'Scanned'), ('mixed', 'Mixed')], help_text='Classification of the source page: born_digital, scanned, or mixed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extracted',
            name='structure_json',
            field=models.JSONField(blank=True, help_text='Rich schema with cell-level data including spans', null=True),
        ),
    ]
