# Generated by Django 6.0.3 on 2026-03-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_rich_fields_to_extracted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.PositiveIntegerField()),
                ('x1', models.FloatField(help_text='Left edge X coordinate (PDF space)')),
                ('y1', models.FloatField(help_text='Bottom edge Y coordinate (PDF space)')),
                ('x2', models.FloatField(help_text='Right edge X coordinate (PDF space)')),
                ('y2', models.FloatField(help_text='Top edge Y coordinate (PDF space)')),
                ('confidence', models.FloatField(blank=True, help_text='YOLO detection confidence (0.0 to 1.0)', null=True)),
                ('source', models.CharField(choices=[('yolo', 'YOLO Detection'), ('manual', 'Manual Selection')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='api.report')),
            ],
            options={
                'ordering': ['page_num', 'created_at'],
            },
        ),
    ]
