# Generated by Django 6.0.3 on 2026-03-11 09:14

from django.db import migrations, models


def set_existing_reports_completed(apps, schema_editor):
    """Set existing reports to extraction_mode='auto' and extraction_status='completed'."""
    Report = apps.get_model('api', 'Report')
    Report.objects.all().update(extraction_mode='auto', extraction_status='completed')


def reverse_set_existing_reports(apps, schema_editor):
    """Reverse migration - no action needed as fields will be removed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_tableselection_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='extraction_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('review', 'Review')], default='auto', help_text='Extraction workflow: auto, manual, or review', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='extraction_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('detecting', 'Detecting'), ('pending_review', 'Pending Review'), ('extracting', 'Extracting'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', help_text='Current processing state of the report', max_length=20),
        ),
        migrations.RunPython(set_existing_reports_completed, reverse_set_existing_reports),
    ]
