# Generated by Django 6.0.3 on 2026-03-12 09:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_extraction_mode_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracted',
            name='selection',
            field=models.ForeignKey(blank=True, help_text='TableSelection this extraction was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='api.tableselection'),
        ),
        migrations.AlterField(
            model_name='tableselection',
            name='x1',
            field=models.FloatField(help_text='Left edge X coordinate (0-100%, top-left origin)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tableselection',
            name='x2',
            field=models.FloatField(help_text='Right edge X coordinate (0-100%, top-left origin)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tableselection',
            name='y1',
            field=models.FloatField(help_text='Top edge Y coordinate (0-100%, top-left origin)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='tableselection',
            name='y2',
            field=models.FloatField(help_text='Bottom edge Y coordinate (0-100%, top-left origin)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
