# Generated by Django 6.0.3 on 2026-03-12 09:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_selection_to_extracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='document',
            field=models.FileField(max_length=255, upload_to=api.models.upload_path),
        ),
    ]
